name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Process Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
